# Use an official Python runtime as a parent image
FROM python:3.8.20

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY phonotactic_corpora_analysis1.py phonotactic_corpora_analysis1.py
COPY legality_principle.py  legality_principle.py 
COPY legality_principle_gbb.py legality_principle_gbb.py 

# Install Jupyter Notebook
RUN pip install jupyter

# Make port 1200 available to the world outside this container
EXPOSE 8888

# Define environment variable
ENV NAME=World

# Run Jupyter Notebook when the container launches
CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]
